apiVersion: apps/v1
kind: Deployment
metadata:
  name: historian
  namespace: routers-dev
  labels:
    app: historian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: historian
  template:
    metadata:
      labels:
        app: historian
    spec:
      containers:
        - name: historian
          image: routers-historian:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq.routers-dev.svc.cluster.local:5672/%2f"
            - name: RABBITMQ_EXCHANGE
              value: "amqprs.example"
            - name: RABBITMQ_ROUTING_KEY
              value: "amq.topic"
            - name: RABBITMQ_QUEUE
              value: "historian"
            - name: VALKEY_URL
              value: "redis://valkey-primary.routers-dev.svc.cluster.local:6379"
            - name: SHARD_PRECISION
              value: "5"
            - name: VALKEY_BATCH
              value: "64"
            - name: VALKEY_BATCH_TIMEOUT_MS
              value: "2"
            - name: RUST_LOG
              value: "debug"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              memory: 256Mi
