download VERSION:
    #!/usr/bin/env bash
    # Set up the target directory
    target_dir="/data/{{VERSION}}"

    # Create the target directory if it doesn't exist
    mkdir -p $target_dir

    # Change into the target directory and perform the download/unzip
    cd $target_dir && wget "https://github.com/evansiroky/timezone-boundary-builder/releases/download/{{VERSION}}/timezones.geojson.zip" && unzip -o timezones.geojson.zip
