name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  PROTOC_VERSION: 3.20.3
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}

      - name: Install Buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Packager
        run: |
          cargo install --locked protoc-gen-buffa-packaging

      - name: Generate Schema
        run: |
          buf generate

      - name: 🧪 Test
        run: cargo nextest run --workspace
